# Generated by Django 5.1 on 2024-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название заголовка', max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, null=True, unique=True, verbose_name='Идентификатор')),
                ('content', models.TextField(help_text='Введите содержимое', max_length=100, verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='catalog/image', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Укажите дату создания', verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, help_text='поставьте галочку если статья опубликована', verbose_name='публикация')),
                ('views', models.IntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'Записи в блоге',
            },
        ),
    ]
