# Generated by Django 5.1 on 2024-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='blog/image', verbose_name='изображение'),
        ),
    ]
