# Generated by Django 5.1 on 2024-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='catalog/image', verbose_name='изображение'),
        ),
    ]
