# Generated by Django 4.2.2 on 2024-10-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_published_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('can_edit_category', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('can_edit_is_published', 'Can edit is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
