# Generated by Django 5.1 on 2024-09-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=0, help_text='номер версии', verbose_name='Номер версии')),
                ('version_name', models.CharField(blank=True, help_text='название версии', max_length=50, null=True, verbose_name='Название версии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('product', models.ForeignKey(blank=True, help_text='продукт, к которому принадлежит версия', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'версия продукта',
                'verbose_name_plural': 'версии продуктов',
            },
        ),
    ]
